[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-economy_pilot_lite"
version = "0.0.3"
description = "Economy Pilot core plugin for Endstone!"

[project.entry-points."endstone"]
economy_pilot_lite = "endstone_economy_pilot_lite:Main"
